name: s2s_forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - dask
  - netcdf4
  - zarr
  - numpy
  - pandas
  - scikit-learn
  - hydra-core
  - wandb
  - tqdm
  - pytest
  - black
  - flake8
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu118
      - torchvision --index-url https://download.pytorch.org/whl/cu118
      - torchaudio --index-url https://download.pytorch.org/whl/cu118
      - -e .       